#ifndef LAB1_MODULE1_RESOURCE_HEADER
#define LAB1_MODULE1_RESOURCE_HEADER

#include <Windows.h>

#define IDR_MODULE1_DIALOG 201
#define IDD_MODULE1_LISTBOX 2001

#endif // !LAB1_MODULE1_RESOURCE_HEADER
