#ifndef LAB1_MODULE2_RESOURCE_HEADER
#define LAB1_MODULE2_RESOURCE_HEADER

#include <Windows.h>

#define IDR_MODULE2_DIALOG 301
#define IDD_MODULE2_TEXT_INPUT 3001

#endif // !LAB1_MODULE2_RESOURCE_HEADER
