#ifndef LAB2_EDITOR_MAIN_MENU
#define LAB2_EDITOR_MAIN_MENU

#include <Framework.h>

#define IDR_EDITOR_MAIN_MENU  101

#define IDM_MAIN_MENU_FILE    1001
#define IDM_MAIN_MENU_OBJECTS 1002
#define IDM_MAIN_MENU_ABOUT   1003

#define IDM_MAIN_MENU_OBJECT_POINT   1010
#define IDM_MAIN_MENU_OBJECT_LINE    1011
#define IDM_MAIN_MENU_OBJECT_RECT    1012
#define IDM_MAIN_MENU_OBJECT_ELLIPSE 1013

#endif // !LAB2_EDITOR_MAIN_MENU
